version: '3.8'

services:
  postgres:
    build: ./server/database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: voiceforgedb
      POSTGRES_PASSWORD: plzIIvHHRaBTTMjcEADwBFc8MVuxbZYO
      POSTGRES_DB: voiceforge_emyw

  redis:
    build: ./server/config
    ports:
      - "6379:6379"

  server:
    build: ./server
    ports:
      - "800:800"
    depends_on:
      - postgres
      - redis
    environment:
    
      DATABASE_URL: postgres://voiceforgedb:plzIIvHHRaBTTMjcEADwBFc8MVuxbZYO@dpg-cn07tfed3nmc7389p0l0-a.oregon-postgres.render.com/voiceforge_emyw
      REDIS_URL: rediss://red-cn07ve6d3nmc7389p7c0:Ush4HtpRUuTdBx59qB5eo2Tdb1rri1e1@oregon-redis.render.com:6379

      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 465
      SMTP_PASSWORD: bkzd cgbb wywn qmvi
      SMTP_FROM: johnkristan01@gmail.com

      AUTHORIZATION_API_KEY: cce9dbd9b9814894880b9299c7528db3
      USER_API_KEY: YazwHTCjhnOMBqwotlb5kFUrx3X2
      
      SERVER_PORT: 800

      ACCESS_TOKEN_JWTSECRET: _Oyxb3GaAeizA8x5CWVr7olRTB4-K2IgSjhBat8Sr1E
      REFRESH_TOKEN_JWTSECRET: MD2D-i7oSSjxjFDQmgVky-AaAcSlxhRT_BaFyzD6kXE
      VERIFICATION_TOKEN_JWTSECRET: b5d1_tfuiV-vZ8-4MwPbE8iGapTBOnm-v9V6FFlZl88
